version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: down_monitor
    ports:
      - 9090:9090
    depends_on:
      - db
    links:
      - db
  clickhouse_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - dbfiles:/var/lib/clickhouse
  
  clickhouse_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

volumes:
  db:
    driver: local
  dbfiles:
    driver: local
